export const MASSAGE_INSERT_REQUEST = "MASSAGE_INSERT_REQUEST";
export const MASSAGE_INSERT_SUCCESS = "MASSAGE_INSERT_SUCCESS";
export const MASSAGE_INSERT_FAIL = "MASSAGE_INSERT_FAIL";

export const FILE_UPLOARD_REQUEST = "FILE_UPLOARD_REQUEST";
export const FILE_UPLOARD_SUCCESS = "FILE_UPLOARD_SUCCESS";
export const FILE_UPLOARD_FAIL = "FILE_UPLOARD_FAIL";
